---
title: "Homework 1"
subtitle: "Research Methods, Spring 2025"
author: "Genevieve DeBell"
format:
  pdf:
    output-file: "debell-g-hwk2-1"
    output-ext:  "pdf"
    header-includes:
      - \usepackage{float}
      - \floatplacement{table}{H}
---



```{r}
#| include: false

if (!require("pacman")) install.packages("pacman")
pacman::p_load(tidyverse, ggplot2, dplyr, lubridate, readr, readxl, hrbrthemes, fixest,
               scales, gganimate, gapminder, gifski, png, tufte, plotly, OECD,
               ggrepel, survey, foreign, devtools, pdftools, kableExtra, modelsummary,
               kableExtra)
```


```{r}
#| include: false
#| eval: true
 
load("/Users/genevievedebell/Documents/GitHub/hwk2/submission3/results/Hwk2_workspace.Rdata")
load("/Users/genevievedebell/Documents/GitHub/hwk2/submission3/results/Hwk2-2_workspace.Rdata")
```

# 1. How many hospitals filed more than one report in the same year? Show your answer as a line graph of the number of hospitals over time.

```{r}
#| echo: false
if (!require("pacman")) install.packages("pacman")
pacman::p_load(tidyverse, ggplot2, dplyr, lubridate)
multi_report_counts <- duplicate.hcris %>%
group_by(fyear) %>%
summarise(num_hospitals = n_distinct(provider_number))

## Plot the number of hospitals filing multiple reports by year
ggplot(multi_report_counts, aes(x = fyear, y = num_hospitals)) +
geom_line(color = "blue", size = 1) +
geom_point(color = "red", size = 2) +
labs(
title = "Hospitals Filing Multiple Reports Per Year",
x = "Year",
y = "Number of Hospitals",
caption = "Source: HCRIS Data (1996 & 2010 Versions)"
) +
theme_minimal()
```

# 2. After removing/combining multiple reports, how many unique hospital IDs (Medicare provider numbers) exist in the data?
```{r}
#| echo: false
fig.unique <- final.hcris.data %>% group_by(year) %>%
  summarize(unique_hospital_count=n()) %>%
  ggplot(aes(x=as.factor(year), y=unique_hospital_count, group=1)) +
  geom_line() +
  labs(
    x="Year",
    y="Number of Hospitals",
    title=""
  ) + theme_bw() +
  scale_y_continuous(labels=scales::comma,limits=c(0,6500)) +
  theme(axis.text.x = element_text(angle=70, hjust=1))
print(fig.unique)
```


